### ISSUE TITLE
Specify versions in pip requirements? 

### ISSUE THREAD

**Issue by kakeith** [rpryzant/causal-bert-pytorch#1]
Hi Reid, 

Thanks for making this package! Can you specify the version numbers in `requirements.txt`? 

Otherwise, when running `python CausalBert.py` I get errors like:
```
Traceback (most recent call last):
  File "CausalBert.py", line 19, in <module>
    from transformers.modeling_bert import BertPreTrainingHeads
ModuleNotFoundError: No module named 'transformers.modeling_bert'
```

Thanks, 
Katie

**Comment by rpryzant** [comment]
https://github.com/rpryzant/causal-bert-pytorch/commit/9c9060f43419ccc8bb90d10c5ad648e2aa44efc3

**Comment by kakeith** [comment]
Thanks! Unfortunately, when I try to run out of the box I'm still getting errors with `pip install  -r requirements.txt`. I'm in the latest version of pip: `pip-21.3.1` and I get the error: 
```
ERROR: No matching distribution found for tensorflow==2.1.0
```

**Comment by rpryzant** [comment]
I've removed the tf dependency (it wasn't needed).

**Comment by kakeith** [comment]
Works now out of the box! Thanks!
