### ISSUE TITLE
C=structured confounder, correct? 

### ISSUE THREAD

**Issue by kakeith** [rpryzant/causal-bert-pytorch#2]
Hey Reid! Using this codebase again finally and just making sure I understand it. 

Comparing https://github.com/rpryzant/causal-bert-pytorch#description to `testdata.csv` I'm assuming: 

- T=treatment
- C=(structured) categorical confounder 
- Y=outcome 

Is that correct? 

What if there is no categorical confounder? Does the code support passing in an array of `nulls` for C? Thanks!

**Comment by rpryzant** [comment]
Thanks for reaching out and sorry for the delay. Yes that is correct! 

This code expects T C and Y to be present for all samples, but if some of your C are null than they could be filtered out in the dataloader: 
https://github.com/rpryzant/causal-bert-pytorch/blob/9153df43f2f55f488df542fd0c64f306d5c36908/CausalBert.py#L278
